# Generated by Django 2.0.2 on 2019-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phnumber',
            field=models.IntegerField(default=0),
        ),
    ]
