# Generated by Django 2.0.2 on 2019-04-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nidphotocopy',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
