# Generated by Django 2.0.2 on 2019-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_nidphotocopy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phnumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(default=880),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nidphotocopy',
            field=models.FileField(default='nid.jpg', upload_to=''),
        ),
    ]
