# Generated by Django 2.0.2 on 2019-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_presentlivingplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='presentlivingplace',
            field=models.CharField(default='provide your present living address', max_length=255),
        ),
    ]
